version: "3.1"
services:
  postgres:
    build:
      context: ./docker/postgres
    ports:
      - 5433:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app
      POSTGRES_PASSWORD: MLsR<v[K<8Vng8(U
    networks:
      - app_net
  redis:
    image: redis:3-alpine
    ports:
      - 6378:6379
    networks:
      - app_net
  nginx:
    build:
      context: ./docker/nginx
    links:
      - php
    ports:
      - 8080:80
    networks:
      - app_net
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    links:
      - redis
    volumes:
      - ./:/var/www/html/
    networks:
      - app_net
  php_worker:
    build:
      context: ./
      dockerfile: ./docker/supervisor/Dockerfile
    links:
      - redis
    restart: always
    volumes:
      - ./docker/supervisor/queue.conf:/etc/supervisor/queue.conf
      - ./:/var/www/html/
    networks:
      - app_net
networks:
  app_net:
    driver: bridge